version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/DLT
    depends_on:
      - mongo

  frontend:
    build:
      context: ../DLT
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - '27017:27017'
